### PR TITLE
find pip based on the current $PATH

### LINKED ISSUE #54: Blocking call to accept-process-output with quit inhibited
I've had this issue recently after updating `anaconda-mode` from melpa. My emacs hung when company-mode tries to auto complete with `anaconda`, and I see message as following in minibar.
```
Blocking call to accept-process-output with quit inhibited.
```

 I guess this is a regression as I saw previous discussion on this issue before. Below is backtrace log on `toggle-debug-on-quit`.
```
Debugger entered--Lisp error: (quit)
  anaconda-mode-bootstrap()
  anaconda-mode-start()
  anaconda-mode-call("complete")
  anaconda-mode-complete()
  company-anaconda-candidates()
  company-anaconda(candidates #("fo" 0 2 (fontified nil)))
  apply(company-anaconda (candidates #("fo" 0 2 (fontified nil))))
  #[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates #("fo" 0 2 (fontified nil))) company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"]()
  funcall(#[0 "\302	!\203\303	\300\"\207\303\304	\300#\207" [(candidates #("fo" 0 2 (fontified nil))) company-backend functionp apply company--multi-backend-adapter] 4 "\n\n(fn)"])
  company-call-backend-raw(candidates #("fo" 0 2 (fontified nil)))
  company--fetch-candidates(#("fo" 0 2 (fontified nil)))
  company-calculate-candidates(#("fo" 0 2 (fontified nil)))
  #[0 "\n\203	\nC\202\n\211\205\245\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\236\314\300\242!\203\230\315\300\242!\211\301\316\f!\240\210\301\242:\204l
\203\230\317\320!\210\202\230
\203t\300\242\2119\203\203\321\322!P\202\211\323\301\242@!\210\324\301\242!\210\325\326\327 \"\210\330\331!\210\332\333\301\242\"\210A\266\202\202\n\207" [(#("fo" 0 2 (fontified nil))) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" " " symbol-name company--update-group-lighter company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix company-lighter] 6 "\n\n(fn)"]()
  funcall(#[0 "\n\203	\nC\202\n\211\205\245\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\236\314\300\242!\203\230\315\300\242!\211\301\316\f!\240\210\301\242:\204l
\203\230\317\320!\210\202\230
\203t\300\242\2119\203\203\321\322!P\202\211\323\301\242@!\210\324\301\242!\210\325\326\327 \"\210\330\331!\210\332\333\301\242\"\210A\266\202\202\n\207" [(#("fo" 0 2 (fontified nil))) (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" " " symbol-name company--update-group-lighter company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix company-lighter] 6 "\n\n(fn)"])
  company--begin-new()
  company--perform()
  #[0 "\300 \207" [company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-idle-begin(#<buffer *scratch*> #<window 3 on *scratch*> 5 3)
  apply(company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 5 3))
  byte-code("r\301\302H\303H\"\210)\301\207" [timer apply 5 6] 4)
  timer-event-handler([t 21662 39799 656946 nil company-idle-begin (#<buffer *scratch*> #<window 3 on *scratch*> 5 3) nil 0])
```

### PR DESCRIPTION
**Pull request by sableloki**
Find the pip binary on $PATH and return the path as a string to Popen. hopefully closes #54

### CODE REVIEW

**Comment by sableloki** [comment]
Here is a screenshot of the part where the tests raise the error i cant see why it wouldnt load
screen shot 2015-01-07 at 2 53 02 am

**Comment by proofit404** [comment]
I hope I correct this issue without breaking python 2.6 compatibility.

**Comment by sableloki** [comment]
look me too, but thats the only way i could see it happening

**Comment by proofit404** [comment]
Are you use mac? What is the problem on this platform? `pip` doesn't run inside `subprocess.Popen`?

**Comment by sableloki** [comment]
yes im on mac and during testing `subprocess.Popen` was throwing errors until rstrip was put in and py2.6 was broken

**Comment by proofit404** [comment]
Can you show this exception?

**Pull request closed without merging**
