### PR TITLE
add documentation on old versions of pip

### PR DESCRIPTION
**Pull request by mijoharas**
This would have saved me some time, hopefully will save someone else time as well.

### CODE REVIEW

**Comment by mijoharas** [comment]
Fixes #136

**Comment by proofit404** [comment]
I guess checking pip version at runtime and show proper error message is better way than writing those lines in the readme. No one read it.

**Comment by mijoharas** [comment]
That's a good point. Googling about I couldn't find which version introduced the `-t` flag, have you got any idea?

**Comment by proofit404** [comment]
It is [1.1 version](https://github.com/pypa/pip/blob/6aab626e7d88c85edb98fa36575aa8272ef3283d/CHANGES.txt#L886-L887). I accept pull requests covered with tests only. You need to write something like `test-old-pip.el` and run it against each supported emacs version both on CPython and IPython. Easiest way to do this is use `ert.sh` test runner from the `tramp` branch.

Feel free to open new pull request when you done.

**Pull request closed without merging**
