### PR TITLE
Remove blocking call `accept-process-output`

### LINKED ISSUE #73: blocking call to accept-process-output
About every 15 seconds I receive the following error when using a Python buffer while anaconda-mode is active:

```Blocking call to accept-process-output with quit inhibited!!```

When this occurs, I have to press ```C-g``` repeatedly to regain keyboard input into the buffer.

I am using the latest Emacs trunk (as of 2015-03-10) on Linux with anaconda-mode version ```20150310.46```. This may be related to #54, but maybe not.

### PR DESCRIPTION
**Pull request by marsam**
Hi:
This removes the blocking call `accept-process-output`, sets `anaconda-mode-port` in the process filter.

Fixes #73

### CODE REVIEW

**Comment by proofit404** [comment]
In general anaconda-mode must sure that server started and bind to the interface. On slow machines first request will be made before anaconda-mode server finish it initialization.

**Comment by marsam** [comment]
HI:
I've updated the commit to check if the anaconda process is started. Tell me if it works

Thanks in advance.

**Comment by proofit404** [comment]
Maybe we can simply [shut-up](https://github.com/cask/shut-up) `accept-process-output`?

**Comment by marsam** [comment]
The purpose of this pull request is to asyncronouly bootstrap the anaconda process, and iirc `shut-up` only allows to silence the output of functions calls.

related: https://github.com/syl20bnr/spacemacs/issues/366

**Comment by proofit404** [comment]
If you want asynchronous server start you should done more job:
- perform command which trigger server start not simply drop it (this must be done without any semaphore variable, in callback passing style)
- server process must clean it filter after successful port number handling
- emacs lisp test suite must cover this asynchronous behavior

**Comment by proofit404** [comment]
Done in the `feature/pypi` branch.

**Pull request closed without merging**
