### PR TITLE
anaconda commands for any object, as if from buffer's top-level context

### PR DESCRIPTION
**Pull request by bmag**
### summary:

This PR adds the commands `anaconda-mode-view-doc-top-level`, `anaconda-mode-usages-top-level` and `anaconda-mode-goto-top-level` (and goto-definitions and goto-assignments).

### behavior changes:

What `anaconda-mode-usages-top-level` does: it is the same as `anaconda-mode-usages`, but instead of using the object at point, it asks the user for an object. So if I'm anywhere inside a file, and I call the command `M-x anaconda-mode-usages-top-level <RET> foo <RET>`, I will see all the usages for `foo`.

Likewise, `anaconda-mode-view-doc-top-level` is analogous to `anaconda-mode-view-doc`. So if I'm in the middle of writing a function call, and I want to view the function's doc without moving the cursor, I can use `anaconda-mode-view-doc-top-level`.

Likewise, `anaconda-mode-goto-top-level` is analogous to `anaconda-mode-goto`. So I can navigate to an object's definition even when it's not the object at point.

### code changes:

- I added an optional CONTEXT-MAKER parameter to `anaconda-mode-call`. A context-maker is a function that returns a list of `(text line-number column-number)` that can be passed to an anaconda command over json-rpc. See `anaconda-mode-context-at-point` for an example.
The default context-maker is `anaconda-mode-context-at-point`, which mimics the original context for `anaconda-mode-call`.

- `anaconda-mode-context-at-point`: context-maker for calling an anaconda command on the object at point.

- `anaconda-mode-context-top-level`: context-maker for calling an anaconda command on any object, as if the call is made from the buffer's top level indentation.

- `anaconda-mode-view-doc-context`: a helper function for viewing an object doc in some context. This is a more general version of the original `anaconda-mode-view-doc`. This is used by `anaconda-mode-view-doc` and `anaconda-mode-view-doc-top-level`.

- `anaconda-mode-view-doc`: changed to use `anaconda-mode-view-doc-context`.

- `anaconda-mode-usages-context`: similar to `anaconda-mode-view-doc-context`

- `anaconda-mode-usages`: similar to `anaconda-mode-view-doc`

- `anaconda-mode-goto-context`: similar to `anaconda-mode-view-doc-context`

- `anaconda-mode-goto`: similar to `anaconda-mode-view-doc`

### what I didn't do:

- I didn't bind the new commands to any keys. I will leave this decision for you.
- I didn't update the README
- I didn't add more contexts. For example, we could add a "calling-function" context, for cases where point is inside a function call, and the user wants to view the function's doc. I did try to make it simple to add new contexts.
- The prompt for the user isn't very nice, I used the plain `read-string` function. I didn't do a fancy prompt, because it's not trivial to decide what prompt is best for which command.

Try it and tell me what you think?

### CODE REVIEW

**Comment by proofit404** [comment]
Interesting features.  But implemented like a hack.  As for me we need extend python side API to achieve this behaviour.  Search in jedi cache with in python code or implement this feature directly in jedi.

Something similar are possible with gnu global and additional python parser.  Did you try ggtags or helm-gtags packages for this goal?

I think we'll find optimal solution.  Any thoughts?

Thanks for contribution.

**Comment by bmag** [comment]
Thanks for quick response :-)

Yeah, I thought it might be a hack, but wasn't sure. I didn't study the python side much, modifying the elisp side seemed easier to me. I also didn't try other tools yet, but now I will.

If we don't add these features to anaconda/jedi, then I need to find tools that do:
1. find defintion of some object
2. show documentation of some object
3. find usages (references) of some object

Looking at helm-gtags docs, looks like it does (1) and (3), but not (2).

I'm gonna look for relevant tools this week or next week, then I'll tell you what I found.

**Comment by proofit404** [comment]
You can also try [pydoc](https://github.com/statmobile/pydoc/) package for documentation lookup.

**Comment by proofit404** [comment]
Any progress?

**Comment by bmag** [comment]
Some progress. I tried a few tools, and settled for a combination of anaconda, pycscope and pylookup.
As I see it, Emacs has several tools for python, each implementing part of what I'm looking for.

- anaconda-mode: works on the thing at point: goto definition, find references and show doc.
- pycscope + helm-cscope: works at project level: goto definition and find references. I also tried helm-gtags and ggtags, but they didn't work as well (even with ctags/pygments plugins).
- pylookup: works at stuff in the standard library, and I think can be used for some 3rd-party modules as well (haven't checked it yet): show doc.
- helm-pydoc: alternative for pylookup, works automatically for installed 3rd-party modules as well.

Of all the above, I think anaconda is better than pycscope at finding definition and references, and sometimes anaconda is also the only option for viewing the doc of a symbol in the current project.
So, I think I will be satisfied if I can find/write commands that do this:
- prompt for a symbol with helm-cscope, then jump to its definition, invoke anaconda (show-usages or show-doc) and jump back to where I was before the prompt.
- prompt for a location in the current file (with ace-jump-mode?), then jump there, invoke anaconda and jump back to where I was before the prompt. This command is for the case of local variables (inside functions) and near-by symbols.

But, I guess such a solution doesn't fall within the scope of anaconda-mode. Seems like I will have to write it myself sometime. As far as I am concerned this PR can be closed.

Some links:
- [pycscope](https://github.com/portante/pycscope)
- [helm-cscope](https://github.com/alpha22jp/helm-cscope.el)
- [helm-gtags](https://github.com/syohex/emacs-helm-gtags)
- [pylookup](https://github.com/tsgates/pylookup)
- [helm-pydoc](https://github.com/syohex/emacs-helm-pydoc)

**Comment by proofit404** [comment]
Ok.  About ace-jump integration - this must be done as a third party plug-in like ac-anaconda and company-anaconda.

**Pull request closed without merging**
